package mybatis.generate.mapper;

import java.util.List;
import mybatis.generate.model.Behaviorsecure;
import mybatis.generate.model.BehaviorsecureExample;
import org.apache.ibatis.annotations.Param;

public interface BehaviorsecureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behaviorsecure
     *
     * @mbg.generated
     */
    long countByExample(BehaviorsecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behaviorsecure
     *
     * @mbg.generated
     */
    int deleteByExample(BehaviorsecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behaviorsecure
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long behaviorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behaviorsecure
     *
     * @mbg.generated
     */
    int insert(Behaviorsecure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behaviorsecure
     *
     * @mbg.generated
     */
    int insertSelective(Behaviorsecure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behaviorsecure
     *
     * @mbg.generated
     */
    List<Behaviorsecure> selectByExample(BehaviorsecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behaviorsecure
     *
     * @mbg.generated
     */
    Behaviorsecure selectByPrimaryKey(Long behaviorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behaviorsecure
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Behaviorsecure record, @Param("example") BehaviorsecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behaviorsecure
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Behaviorsecure record, @Param("example") BehaviorsecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behaviorsecure
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Behaviorsecure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table behaviorsecure
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Behaviorsecure record);
}