package mybatis.generate.mapper;

import java.util.List;
import mybatis.generate.model.Recognisesecure;
import mybatis.generate.model.RecognisesecureExample;
import org.apache.ibatis.annotations.Param;

public interface RecognisesecureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    long countByExample(RecognisesecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    int deleteByExample(RecognisesecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String recogniseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    int insert(Recognisesecure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    int insertSelective(Recognisesecure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    List<Recognisesecure> selectByExampleWithBLOBs(RecognisesecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    List<Recognisesecure> selectByExample(RecognisesecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    Recognisesecure selectByPrimaryKey(String recogniseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Recognisesecure record, @Param("example") RecognisesecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Recognisesecure record, @Param("example") RecognisesecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Recognisesecure record, @Param("example") RecognisesecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Recognisesecure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Recognisesecure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Recognisesecure record);
}