package mybatis.generate.mapper;

import java.util.List;
import mybatis.generate.model.Redeemsecure;
import mybatis.generate.model.RedeemsecureExample;
import org.apache.ibatis.annotations.Param;

public interface RedeemsecureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeemsecure
     *
     * @mbg.generated
     */
    long countByExample(RedeemsecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeemsecure
     *
     * @mbg.generated
     */
    int deleteByExample(RedeemsecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeemsecure
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String redeemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeemsecure
     *
     * @mbg.generated
     */
    int insert(Redeemsecure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeemsecure
     *
     * @mbg.generated
     */
    int insertSelective(Redeemsecure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeemsecure
     *
     * @mbg.generated
     */
    List<Redeemsecure> selectByExample(RedeemsecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeemsecure
     *
     * @mbg.generated
     */
    Redeemsecure selectByPrimaryKey(String redeemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeemsecure
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Redeemsecure record, @Param("example") RedeemsecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeemsecure
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Redeemsecure record, @Param("example") RedeemsecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeemsecure
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Redeemsecure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table redeemsecure
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Redeemsecure record);
}