package mybatis.generate.mapper;

import java.util.List;
import mybatis.generate.model.Walletsecure;
import mybatis.generate.model.WalletsecureExample;
import org.apache.ibatis.annotations.Param;

public interface WalletsecureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walletsecure
     *
     * @mbg.generated
     */
    long countByExample(WalletsecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walletsecure
     *
     * @mbg.generated
     */
    int deleteByExample(WalletsecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walletsecure
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long walletId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walletsecure
     *
     * @mbg.generated
     */
    int insert(Walletsecure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walletsecure
     *
     * @mbg.generated
     */
    int insertSelective(Walletsecure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walletsecure
     *
     * @mbg.generated
     */
    List<Walletsecure> selectByExample(WalletsecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walletsecure
     *
     * @mbg.generated
     */
    Walletsecure selectByPrimaryKey(Long walletId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walletsecure
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Walletsecure record, @Param("example") WalletsecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walletsecure
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Walletsecure record, @Param("example") WalletsecureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walletsecure
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Walletsecure record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table walletsecure
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Walletsecure record);
}