package mybatis.generate.model;

import java.util.Date;

public class Behaviorsecure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behaviorsecure.behavior_id
     *
     * @mbg.generated
     */
    private Long behaviorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behaviorsecure.client_id
     *
     * @mbg.generated
     */
    private Integer clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behaviorsecure.category_name
     *
     * @mbg.generated
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behaviorsecure.subcategory_name
     *
     * @mbg.generated
     */
    private String subcategoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behaviorsecure.delete_type
     *
     * @mbg.generated
     */
    private String deleteType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behaviorsecure.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behaviorsecure.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behaviorsecure.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column behaviorsecure.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behaviorsecure.behavior_id
     *
     * @return the value of behaviorsecure.behavior_id
     *
     * @mbg.generated
     */
    public Long getBehaviorId() {
        return behaviorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behaviorsecure.behavior_id
     *
     * @param behaviorId the value for behaviorsecure.behavior_id
     *
     * @mbg.generated
     */
    public void setBehaviorId(Long behaviorId) {
        this.behaviorId = behaviorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behaviorsecure.client_id
     *
     * @return the value of behaviorsecure.client_id
     *
     * @mbg.generated
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behaviorsecure.client_id
     *
     * @param clientId the value for behaviorsecure.client_id
     *
     * @mbg.generated
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behaviorsecure.category_name
     *
     * @return the value of behaviorsecure.category_name
     *
     * @mbg.generated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behaviorsecure.category_name
     *
     * @param categoryName the value for behaviorsecure.category_name
     *
     * @mbg.generated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behaviorsecure.subcategory_name
     *
     * @return the value of behaviorsecure.subcategory_name
     *
     * @mbg.generated
     */
    public String getSubcategoryName() {
        return subcategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behaviorsecure.subcategory_name
     *
     * @param subcategoryName the value for behaviorsecure.subcategory_name
     *
     * @mbg.generated
     */
    public void setSubcategoryName(String subcategoryName) {
        this.subcategoryName = subcategoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behaviorsecure.delete_type
     *
     * @return the value of behaviorsecure.delete_type
     *
     * @mbg.generated
     */
    public String getDeleteType() {
        return deleteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behaviorsecure.delete_type
     *
     * @param deleteType the value for behaviorsecure.delete_type
     *
     * @mbg.generated
     */
    public void setDeleteType(String deleteType) {
        this.deleteType = deleteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behaviorsecure.create_user
     *
     * @return the value of behaviorsecure.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behaviorsecure.create_user
     *
     * @param createUser the value for behaviorsecure.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behaviorsecure.create_time
     *
     * @return the value of behaviorsecure.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behaviorsecure.create_time
     *
     * @param createTime the value for behaviorsecure.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behaviorsecure.update_user
     *
     * @return the value of behaviorsecure.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behaviorsecure.update_user
     *
     * @param updateUser the value for behaviorsecure.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column behaviorsecure.update_time
     *
     * @return the value of behaviorsecure.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column behaviorsecure.update_time
     *
     * @param updateTime the value for behaviorsecure.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}