package mybatis.generate.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ClientsecureExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    public ClientsecureExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClientIdIsNull() {
            addCriterion("client_id is null");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("client_id is not null");
            return (Criteria) this;
        }

        public Criteria andClientIdEqualTo(Integer value) {
            addCriterion("client_id =", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotEqualTo(Integer value) {
            addCriterion("client_id <>", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThan(Integer value) {
            addCriterion("client_id >", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("client_id >=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThan(Integer value) {
            addCriterion("client_id <", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThanOrEqualTo(Integer value) {
            addCriterion("client_id <=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdIn(List<Integer> values) {
            addCriterion("client_id in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotIn(List<Integer> values) {
            addCriterion("client_id not in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdBetween(Integer value1, Integer value2) {
            addCriterion("client_id between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotBetween(Integer value1, Integer value2) {
            addCriterion("client_id not between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdIsNull() {
            addCriterion("organization_id is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdIsNotNull() {
            addCriterion("organization_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdEqualTo(String value) {
            addCriterion("organization_id =", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdNotEqualTo(String value) {
            addCriterion("organization_id <>", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdGreaterThan(String value) {
            addCriterion("organization_id >", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdGreaterThanOrEqualTo(String value) {
            addCriterion("organization_id >=", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdLessThan(String value) {
            addCriterion("organization_id <", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdLessThanOrEqualTo(String value) {
            addCriterion("organization_id <=", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdLike(String value) {
            addCriterion("organization_id like", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdNotLike(String value) {
            addCriterion("organization_id not like", value, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdIn(List<String> values) {
            addCriterion("organization_id in", values, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdNotIn(List<String> values) {
            addCriterion("organization_id not in", values, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdBetween(String value1, String value2) {
            addCriterion("organization_id between", value1, value2, "organizationId");
            return (Criteria) this;
        }

        public Criteria andOrganizationIdNotBetween(String value1, String value2) {
            addCriterion("organization_id not between", value1, value2, "organizationId");
            return (Criteria) this;
        }

        public Criteria andClientNameIsNull() {
            addCriterion("client_name is null");
            return (Criteria) this;
        }

        public Criteria andClientNameIsNotNull() {
            addCriterion("client_name is not null");
            return (Criteria) this;
        }

        public Criteria andClientNameEqualTo(String value) {
            addCriterion("client_name =", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotEqualTo(String value) {
            addCriterion("client_name <>", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameGreaterThan(String value) {
            addCriterion("client_name >", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameGreaterThanOrEqualTo(String value) {
            addCriterion("client_name >=", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameLessThan(String value) {
            addCriterion("client_name <", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameLessThanOrEqualTo(String value) {
            addCriterion("client_name <=", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameLike(String value) {
            addCriterion("client_name like", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotLike(String value) {
            addCriterion("client_name not like", value, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameIn(List<String> values) {
            addCriterion("client_name in", values, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotIn(List<String> values) {
            addCriterion("client_name not in", values, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameBetween(String value1, String value2) {
            addCriterion("client_name between", value1, value2, "clientName");
            return (Criteria) this;
        }

        public Criteria andClientNameNotBetween(String value1, String value2) {
            addCriterion("client_name not between", value1, value2, "clientName");
            return (Criteria) this;
        }

        public Criteria andContactEmailIsNull() {
            addCriterion("contact_email is null");
            return (Criteria) this;
        }

        public Criteria andContactEmailIsNotNull() {
            addCriterion("contact_email is not null");
            return (Criteria) this;
        }

        public Criteria andContactEmailEqualTo(String value) {
            addCriterion("contact_email =", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailNotEqualTo(String value) {
            addCriterion("contact_email <>", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailGreaterThan(String value) {
            addCriterion("contact_email >", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailGreaterThanOrEqualTo(String value) {
            addCriterion("contact_email >=", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailLessThan(String value) {
            addCriterion("contact_email <", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailLessThanOrEqualTo(String value) {
            addCriterion("contact_email <=", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailLike(String value) {
            addCriterion("contact_email like", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailNotLike(String value) {
            addCriterion("contact_email not like", value, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailIn(List<String> values) {
            addCriterion("contact_email in", values, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailNotIn(List<String> values) {
            addCriterion("contact_email not in", values, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailBetween(String value1, String value2) {
            addCriterion("contact_email between", value1, value2, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andContactEmailNotBetween(String value1, String value2) {
            addCriterion("contact_email not between", value1, value2, "contactEmail");
            return (Criteria) this;
        }

        public Criteria andWalletIdIsNull() {
            addCriterion("wallet_id is null");
            return (Criteria) this;
        }

        public Criteria andWalletIdIsNotNull() {
            addCriterion("wallet_id is not null");
            return (Criteria) this;
        }

        public Criteria andWalletIdEqualTo(Long value) {
            addCriterion("wallet_id =", value, "walletId");
            return (Criteria) this;
        }

        public Criteria andWalletIdNotEqualTo(Long value) {
            addCriterion("wallet_id <>", value, "walletId");
            return (Criteria) this;
        }

        public Criteria andWalletIdGreaterThan(Long value) {
            addCriterion("wallet_id >", value, "walletId");
            return (Criteria) this;
        }

        public Criteria andWalletIdGreaterThanOrEqualTo(Long value) {
            addCriterion("wallet_id >=", value, "walletId");
            return (Criteria) this;
        }

        public Criteria andWalletIdLessThan(Long value) {
            addCriterion("wallet_id <", value, "walletId");
            return (Criteria) this;
        }

        public Criteria andWalletIdLessThanOrEqualTo(Long value) {
            addCriterion("wallet_id <=", value, "walletId");
            return (Criteria) this;
        }

        public Criteria andWalletIdIn(List<Long> values) {
            addCriterion("wallet_id in", values, "walletId");
            return (Criteria) this;
        }

        public Criteria andWalletIdNotIn(List<Long> values) {
            addCriterion("wallet_id not in", values, "walletId");
            return (Criteria) this;
        }

        public Criteria andWalletIdBetween(Long value1, Long value2) {
            addCriterion("wallet_id between", value1, value2, "walletId");
            return (Criteria) this;
        }

        public Criteria andWalletIdNotBetween(Long value1, Long value2) {
            addCriterion("wallet_id not between", value1, value2, "walletId");
            return (Criteria) this;
        }

        public Criteria andUserInitialCoinIsNull() {
            addCriterion("user_initial_coin is null");
            return (Criteria) this;
        }

        public Criteria andUserInitialCoinIsNotNull() {
            addCriterion("user_initial_coin is not null");
            return (Criteria) this;
        }

        public Criteria andUserInitialCoinEqualTo(Integer value) {
            addCriterion("user_initial_coin =", value, "userInitialCoin");
            return (Criteria) this;
        }

        public Criteria andUserInitialCoinNotEqualTo(Integer value) {
            addCriterion("user_initial_coin <>", value, "userInitialCoin");
            return (Criteria) this;
        }

        public Criteria andUserInitialCoinGreaterThan(Integer value) {
            addCriterion("user_initial_coin >", value, "userInitialCoin");
            return (Criteria) this;
        }

        public Criteria andUserInitialCoinGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_initial_coin >=", value, "userInitialCoin");
            return (Criteria) this;
        }

        public Criteria andUserInitialCoinLessThan(Integer value) {
            addCriterion("user_initial_coin <", value, "userInitialCoin");
            return (Criteria) this;
        }

        public Criteria andUserInitialCoinLessThanOrEqualTo(Integer value) {
            addCriterion("user_initial_coin <=", value, "userInitialCoin");
            return (Criteria) this;
        }

        public Criteria andUserInitialCoinIn(List<Integer> values) {
            addCriterion("user_initial_coin in", values, "userInitialCoin");
            return (Criteria) this;
        }

        public Criteria andUserInitialCoinNotIn(List<Integer> values) {
            addCriterion("user_initial_coin not in", values, "userInitialCoin");
            return (Criteria) this;
        }

        public Criteria andUserInitialCoinBetween(Integer value1, Integer value2) {
            addCriterion("user_initial_coin between", value1, value2, "userInitialCoin");
            return (Criteria) this;
        }

        public Criteria andUserInitialCoinNotBetween(Integer value1, Integer value2) {
            addCriterion("user_initial_coin not between", value1, value2, "userInitialCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinIsNull() {
            addCriterion("recognise_coin is null");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinIsNotNull() {
            addCriterion("recognise_coin is not null");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinEqualTo(Integer value) {
            addCriterion("recognise_coin =", value, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinNotEqualTo(Integer value) {
            addCriterion("recognise_coin <>", value, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinGreaterThan(Integer value) {
            addCriterion("recognise_coin >", value, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinGreaterThanOrEqualTo(Integer value) {
            addCriterion("recognise_coin >=", value, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinLessThan(Integer value) {
            addCriterion("recognise_coin <", value, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinLessThanOrEqualTo(Integer value) {
            addCriterion("recognise_coin <=", value, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinIn(List<Integer> values) {
            addCriterion("recognise_coin in", values, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinNotIn(List<Integer> values) {
            addCriterion("recognise_coin not in", values, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinBetween(Integer value1, Integer value2) {
            addCriterion("recognise_coin between", value1, value2, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinNotBetween(Integer value1, Integer value2) {
            addCriterion("recognise_coin not between", value1, value2, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andCoinResetIntervalIsNull() {
            addCriterion("coin_reset_interval is null");
            return (Criteria) this;
        }

        public Criteria andCoinResetIntervalIsNotNull() {
            addCriterion("coin_reset_interval is not null");
            return (Criteria) this;
        }

        public Criteria andCoinResetIntervalEqualTo(String value) {
            addCriterion("coin_reset_interval =", value, "coinResetInterval");
            return (Criteria) this;
        }

        public Criteria andCoinResetIntervalNotEqualTo(String value) {
            addCriterion("coin_reset_interval <>", value, "coinResetInterval");
            return (Criteria) this;
        }

        public Criteria andCoinResetIntervalGreaterThan(String value) {
            addCriterion("coin_reset_interval >", value, "coinResetInterval");
            return (Criteria) this;
        }

        public Criteria andCoinResetIntervalGreaterThanOrEqualTo(String value) {
            addCriterion("coin_reset_interval >=", value, "coinResetInterval");
            return (Criteria) this;
        }

        public Criteria andCoinResetIntervalLessThan(String value) {
            addCriterion("coin_reset_interval <", value, "coinResetInterval");
            return (Criteria) this;
        }

        public Criteria andCoinResetIntervalLessThanOrEqualTo(String value) {
            addCriterion("coin_reset_interval <=", value, "coinResetInterval");
            return (Criteria) this;
        }

        public Criteria andCoinResetIntervalLike(String value) {
            addCriterion("coin_reset_interval like", value, "coinResetInterval");
            return (Criteria) this;
        }

        public Criteria andCoinResetIntervalNotLike(String value) {
            addCriterion("coin_reset_interval not like", value, "coinResetInterval");
            return (Criteria) this;
        }

        public Criteria andCoinResetIntervalIn(List<String> values) {
            addCriterion("coin_reset_interval in", values, "coinResetInterval");
            return (Criteria) this;
        }

        public Criteria andCoinResetIntervalNotIn(List<String> values) {
            addCriterion("coin_reset_interval not in", values, "coinResetInterval");
            return (Criteria) this;
        }

        public Criteria andCoinResetIntervalBetween(String value1, String value2) {
            addCriterion("coin_reset_interval between", value1, value2, "coinResetInterval");
            return (Criteria) this;
        }

        public Criteria andCoinResetIntervalNotBetween(String value1, String value2) {
            addCriterion("coin_reset_interval not between", value1, value2, "coinResetInterval");
            return (Criteria) this;
        }

        public Criteria andCoinResetTypeIsNull() {
            addCriterion("coin_reset_type is null");
            return (Criteria) this;
        }

        public Criteria andCoinResetTypeIsNotNull() {
            addCriterion("coin_reset_type is not null");
            return (Criteria) this;
        }

        public Criteria andCoinResetTypeEqualTo(String value) {
            addCriterion("coin_reset_type =", value, "coinResetType");
            return (Criteria) this;
        }

        public Criteria andCoinResetTypeNotEqualTo(String value) {
            addCriterion("coin_reset_type <>", value, "coinResetType");
            return (Criteria) this;
        }

        public Criteria andCoinResetTypeGreaterThan(String value) {
            addCriterion("coin_reset_type >", value, "coinResetType");
            return (Criteria) this;
        }

        public Criteria andCoinResetTypeGreaterThanOrEqualTo(String value) {
            addCriterion("coin_reset_type >=", value, "coinResetType");
            return (Criteria) this;
        }

        public Criteria andCoinResetTypeLessThan(String value) {
            addCriterion("coin_reset_type <", value, "coinResetType");
            return (Criteria) this;
        }

        public Criteria andCoinResetTypeLessThanOrEqualTo(String value) {
            addCriterion("coin_reset_type <=", value, "coinResetType");
            return (Criteria) this;
        }

        public Criteria andCoinResetTypeLike(String value) {
            addCriterion("coin_reset_type like", value, "coinResetType");
            return (Criteria) this;
        }

        public Criteria andCoinResetTypeNotLike(String value) {
            addCriterion("coin_reset_type not like", value, "coinResetType");
            return (Criteria) this;
        }

        public Criteria andCoinResetTypeIn(List<String> values) {
            addCriterion("coin_reset_type in", values, "coinResetType");
            return (Criteria) this;
        }

        public Criteria andCoinResetTypeNotIn(List<String> values) {
            addCriterion("coin_reset_type not in", values, "coinResetType");
            return (Criteria) this;
        }

        public Criteria andCoinResetTypeBetween(String value1, String value2) {
            addCriterion("coin_reset_type between", value1, value2, "coinResetType");
            return (Criteria) this;
        }

        public Criteria andCoinResetTypeNotBetween(String value1, String value2) {
            addCriterion("coin_reset_type not between", value1, value2, "coinResetType");
            return (Criteria) this;
        }

        public Criteria andDeleteTypeIsNull() {
            addCriterion("delete_type is null");
            return (Criteria) this;
        }

        public Criteria andDeleteTypeIsNotNull() {
            addCriterion("delete_type is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteTypeEqualTo(String value) {
            addCriterion("delete_type =", value, "deleteType");
            return (Criteria) this;
        }

        public Criteria andDeleteTypeNotEqualTo(String value) {
            addCriterion("delete_type <>", value, "deleteType");
            return (Criteria) this;
        }

        public Criteria andDeleteTypeGreaterThan(String value) {
            addCriterion("delete_type >", value, "deleteType");
            return (Criteria) this;
        }

        public Criteria andDeleteTypeGreaterThanOrEqualTo(String value) {
            addCriterion("delete_type >=", value, "deleteType");
            return (Criteria) this;
        }

        public Criteria andDeleteTypeLessThan(String value) {
            addCriterion("delete_type <", value, "deleteType");
            return (Criteria) this;
        }

        public Criteria andDeleteTypeLessThanOrEqualTo(String value) {
            addCriterion("delete_type <=", value, "deleteType");
            return (Criteria) this;
        }

        public Criteria andDeleteTypeLike(String value) {
            addCriterion("delete_type like", value, "deleteType");
            return (Criteria) this;
        }

        public Criteria andDeleteTypeNotLike(String value) {
            addCriterion("delete_type not like", value, "deleteType");
            return (Criteria) this;
        }

        public Criteria andDeleteTypeIn(List<String> values) {
            addCriterion("delete_type in", values, "deleteType");
            return (Criteria) this;
        }

        public Criteria andDeleteTypeNotIn(List<String> values) {
            addCriterion("delete_type not in", values, "deleteType");
            return (Criteria) this;
        }

        public Criteria andDeleteTypeBetween(String value1, String value2) {
            addCriterion("delete_type between", value1, value2, "deleteType");
            return (Criteria) this;
        }

        public Criteria andDeleteTypeNotBetween(String value1, String value2) {
            addCriterion("delete_type not between", value1, value2, "deleteType");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clientsecure
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clientsecure
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}