package mybatis.generate.model;

import java.util.Date;

public class Clientsecure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientsecure.client_id
     *
     * @mbg.generated
     */
    private Integer clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientsecure.organization_id
     *
     * @mbg.generated
     */
    private String organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientsecure.client_name
     *
     * @mbg.generated
     */
    private String clientName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientsecure.contact_email
     *
     * @mbg.generated
     */
    private String contactEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientsecure.wallet_id
     *
     * @mbg.generated
     */
    private Long walletId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientsecure.user_initial_coin
     *
     * @mbg.generated
     */
    private Integer userInitialCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientsecure.recognise_coin
     *
     * @mbg.generated
     */
    private Integer recogniseCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientsecure.coin_reset_interval
     *
     * @mbg.generated
     */
    private String coinResetInterval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientsecure.coin_reset_type
     *
     * @mbg.generated
     */
    private String coinResetType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientsecure.delete_type
     *
     * @mbg.generated
     */
    private String deleteType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientsecure.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientsecure.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientsecure.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clientsecure.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientsecure.client_id
     *
     * @return the value of clientsecure.client_id
     *
     * @mbg.generated
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientsecure.client_id
     *
     * @param clientId the value for clientsecure.client_id
     *
     * @mbg.generated
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientsecure.organization_id
     *
     * @return the value of clientsecure.organization_id
     *
     * @mbg.generated
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientsecure.organization_id
     *
     * @param organizationId the value for clientsecure.organization_id
     *
     * @mbg.generated
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientsecure.client_name
     *
     * @return the value of clientsecure.client_name
     *
     * @mbg.generated
     */
    public String getClientName() {
        return clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientsecure.client_name
     *
     * @param clientName the value for clientsecure.client_name
     *
     * @mbg.generated
     */
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientsecure.contact_email
     *
     * @return the value of clientsecure.contact_email
     *
     * @mbg.generated
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientsecure.contact_email
     *
     * @param contactEmail the value for clientsecure.contact_email
     *
     * @mbg.generated
     */
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientsecure.wallet_id
     *
     * @return the value of clientsecure.wallet_id
     *
     * @mbg.generated
     */
    public Long getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientsecure.wallet_id
     *
     * @param walletId the value for clientsecure.wallet_id
     *
     * @mbg.generated
     */
    public void setWalletId(Long walletId) {
        this.walletId = walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientsecure.user_initial_coin
     *
     * @return the value of clientsecure.user_initial_coin
     *
     * @mbg.generated
     */
    public Integer getUserInitialCoin() {
        return userInitialCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientsecure.user_initial_coin
     *
     * @param userInitialCoin the value for clientsecure.user_initial_coin
     *
     * @mbg.generated
     */
    public void setUserInitialCoin(Integer userInitialCoin) {
        this.userInitialCoin = userInitialCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientsecure.recognise_coin
     *
     * @return the value of clientsecure.recognise_coin
     *
     * @mbg.generated
     */
    public Integer getRecogniseCoin() {
        return recogniseCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientsecure.recognise_coin
     *
     * @param recogniseCoin the value for clientsecure.recognise_coin
     *
     * @mbg.generated
     */
    public void setRecogniseCoin(Integer recogniseCoin) {
        this.recogniseCoin = recogniseCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientsecure.coin_reset_interval
     *
     * @return the value of clientsecure.coin_reset_interval
     *
     * @mbg.generated
     */
    public String getCoinResetInterval() {
        return coinResetInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientsecure.coin_reset_interval
     *
     * @param coinResetInterval the value for clientsecure.coin_reset_interval
     *
     * @mbg.generated
     */
    public void setCoinResetInterval(String coinResetInterval) {
        this.coinResetInterval = coinResetInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientsecure.coin_reset_type
     *
     * @return the value of clientsecure.coin_reset_type
     *
     * @mbg.generated
     */
    public String getCoinResetType() {
        return coinResetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientsecure.coin_reset_type
     *
     * @param coinResetType the value for clientsecure.coin_reset_type
     *
     * @mbg.generated
     */
    public void setCoinResetType(String coinResetType) {
        this.coinResetType = coinResetType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientsecure.delete_type
     *
     * @return the value of clientsecure.delete_type
     *
     * @mbg.generated
     */
    public String getDeleteType() {
        return deleteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientsecure.delete_type
     *
     * @param deleteType the value for clientsecure.delete_type
     *
     * @mbg.generated
     */
    public void setDeleteType(String deleteType) {
        this.deleteType = deleteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientsecure.create_user
     *
     * @return the value of clientsecure.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientsecure.create_user
     *
     * @param createUser the value for clientsecure.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientsecure.create_time
     *
     * @return the value of clientsecure.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientsecure.create_time
     *
     * @param createTime the value for clientsecure.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientsecure.update_user
     *
     * @return the value of clientsecure.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientsecure.update_user
     *
     * @param updateUser the value for clientsecure.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clientsecure.update_time
     *
     * @return the value of clientsecure.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clientsecure.update_time
     *
     * @param updateTime the value for clientsecure.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}