package mybatis.generate.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RecognisesecureExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    public RecognisesecureExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRecogniseIdIsNull() {
            addCriterion("recognise_id is null");
            return (Criteria) this;
        }

        public Criteria andRecogniseIdIsNotNull() {
            addCriterion("recognise_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecogniseIdEqualTo(String value) {
            addCriterion("recognise_id =", value, "recogniseId");
            return (Criteria) this;
        }

        public Criteria andRecogniseIdNotEqualTo(String value) {
            addCriterion("recognise_id <>", value, "recogniseId");
            return (Criteria) this;
        }

        public Criteria andRecogniseIdGreaterThan(String value) {
            addCriterion("recognise_id >", value, "recogniseId");
            return (Criteria) this;
        }

        public Criteria andRecogniseIdGreaterThanOrEqualTo(String value) {
            addCriterion("recognise_id >=", value, "recogniseId");
            return (Criteria) this;
        }

        public Criteria andRecogniseIdLessThan(String value) {
            addCriterion("recognise_id <", value, "recogniseId");
            return (Criteria) this;
        }

        public Criteria andRecogniseIdLessThanOrEqualTo(String value) {
            addCriterion("recognise_id <=", value, "recogniseId");
            return (Criteria) this;
        }

        public Criteria andRecogniseIdLike(String value) {
            addCriterion("recognise_id like", value, "recogniseId");
            return (Criteria) this;
        }

        public Criteria andRecogniseIdNotLike(String value) {
            addCriterion("recognise_id not like", value, "recogniseId");
            return (Criteria) this;
        }

        public Criteria andRecogniseIdIn(List<String> values) {
            addCriterion("recognise_id in", values, "recogniseId");
            return (Criteria) this;
        }

        public Criteria andRecogniseIdNotIn(List<String> values) {
            addCriterion("recognise_id not in", values, "recogniseId");
            return (Criteria) this;
        }

        public Criteria andRecogniseIdBetween(String value1, String value2) {
            addCriterion("recognise_id between", value1, value2, "recogniseId");
            return (Criteria) this;
        }

        public Criteria andRecogniseIdNotBetween(String value1, String value2) {
            addCriterion("recognise_id not between", value1, value2, "recogniseId");
            return (Criteria) this;
        }

        public Criteria andSenderUserIdIsNull() {
            addCriterion("sender_user_id is null");
            return (Criteria) this;
        }

        public Criteria andSenderUserIdIsNotNull() {
            addCriterion("sender_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andSenderUserIdEqualTo(Long value) {
            addCriterion("sender_user_id =", value, "senderUserId");
            return (Criteria) this;
        }

        public Criteria andSenderUserIdNotEqualTo(Long value) {
            addCriterion("sender_user_id <>", value, "senderUserId");
            return (Criteria) this;
        }

        public Criteria andSenderUserIdGreaterThan(Long value) {
            addCriterion("sender_user_id >", value, "senderUserId");
            return (Criteria) this;
        }

        public Criteria andSenderUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sender_user_id >=", value, "senderUserId");
            return (Criteria) this;
        }

        public Criteria andSenderUserIdLessThan(Long value) {
            addCriterion("sender_user_id <", value, "senderUserId");
            return (Criteria) this;
        }

        public Criteria andSenderUserIdLessThanOrEqualTo(Long value) {
            addCriterion("sender_user_id <=", value, "senderUserId");
            return (Criteria) this;
        }

        public Criteria andSenderUserIdIn(List<Long> values) {
            addCriterion("sender_user_id in", values, "senderUserId");
            return (Criteria) this;
        }

        public Criteria andSenderUserIdNotIn(List<Long> values) {
            addCriterion("sender_user_id not in", values, "senderUserId");
            return (Criteria) this;
        }

        public Criteria andSenderUserIdBetween(Long value1, Long value2) {
            addCriterion("sender_user_id between", value1, value2, "senderUserId");
            return (Criteria) this;
        }

        public Criteria andSenderUserIdNotBetween(Long value1, Long value2) {
            addCriterion("sender_user_id not between", value1, value2, "senderUserId");
            return (Criteria) this;
        }

        public Criteria andRecipientUserIdIsNull() {
            addCriterion("recipient_user_id is null");
            return (Criteria) this;
        }

        public Criteria andRecipientUserIdIsNotNull() {
            addCriterion("recipient_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andRecipientUserIdEqualTo(Long value) {
            addCriterion("recipient_user_id =", value, "recipientUserId");
            return (Criteria) this;
        }

        public Criteria andRecipientUserIdNotEqualTo(Long value) {
            addCriterion("recipient_user_id <>", value, "recipientUserId");
            return (Criteria) this;
        }

        public Criteria andRecipientUserIdGreaterThan(Long value) {
            addCriterion("recipient_user_id >", value, "recipientUserId");
            return (Criteria) this;
        }

        public Criteria andRecipientUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("recipient_user_id >=", value, "recipientUserId");
            return (Criteria) this;
        }

        public Criteria andRecipientUserIdLessThan(Long value) {
            addCriterion("recipient_user_id <", value, "recipientUserId");
            return (Criteria) this;
        }

        public Criteria andRecipientUserIdLessThanOrEqualTo(Long value) {
            addCriterion("recipient_user_id <=", value, "recipientUserId");
            return (Criteria) this;
        }

        public Criteria andRecipientUserIdIn(List<Long> values) {
            addCriterion("recipient_user_id in", values, "recipientUserId");
            return (Criteria) this;
        }

        public Criteria andRecipientUserIdNotIn(List<Long> values) {
            addCriterion("recipient_user_id not in", values, "recipientUserId");
            return (Criteria) this;
        }

        public Criteria andRecipientUserIdBetween(Long value1, Long value2) {
            addCriterion("recipient_user_id between", value1, value2, "recipientUserId");
            return (Criteria) this;
        }

        public Criteria andRecipientUserIdNotBetween(Long value1, Long value2) {
            addCriterion("recipient_user_id not between", value1, value2, "recipientUserId");
            return (Criteria) this;
        }

        public Criteria andBehaviorIdIsNull() {
            addCriterion("behavior_id is null");
            return (Criteria) this;
        }

        public Criteria andBehaviorIdIsNotNull() {
            addCriterion("behavior_id is not null");
            return (Criteria) this;
        }

        public Criteria andBehaviorIdEqualTo(Long value) {
            addCriterion("behavior_id =", value, "behaviorId");
            return (Criteria) this;
        }

        public Criteria andBehaviorIdNotEqualTo(Long value) {
            addCriterion("behavior_id <>", value, "behaviorId");
            return (Criteria) this;
        }

        public Criteria andBehaviorIdGreaterThan(Long value) {
            addCriterion("behavior_id >", value, "behaviorId");
            return (Criteria) this;
        }

        public Criteria andBehaviorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("behavior_id >=", value, "behaviorId");
            return (Criteria) this;
        }

        public Criteria andBehaviorIdLessThan(Long value) {
            addCriterion("behavior_id <", value, "behaviorId");
            return (Criteria) this;
        }

        public Criteria andBehaviorIdLessThanOrEqualTo(Long value) {
            addCriterion("behavior_id <=", value, "behaviorId");
            return (Criteria) this;
        }

        public Criteria andBehaviorIdIn(List<Long> values) {
            addCriterion("behavior_id in", values, "behaviorId");
            return (Criteria) this;
        }

        public Criteria andBehaviorIdNotIn(List<Long> values) {
            addCriterion("behavior_id not in", values, "behaviorId");
            return (Criteria) this;
        }

        public Criteria andBehaviorIdBetween(Long value1, Long value2) {
            addCriterion("behavior_id between", value1, value2, "behaviorId");
            return (Criteria) this;
        }

        public Criteria andBehaviorIdNotBetween(Long value1, Long value2) {
            addCriterion("behavior_id not between", value1, value2, "behaviorId");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinIsNull() {
            addCriterion("recognise_coin is null");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinIsNotNull() {
            addCriterion("recognise_coin is not null");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinEqualTo(Integer value) {
            addCriterion("recognise_coin =", value, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinNotEqualTo(Integer value) {
            addCriterion("recognise_coin <>", value, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinGreaterThan(Integer value) {
            addCriterion("recognise_coin >", value, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinGreaterThanOrEqualTo(Integer value) {
            addCriterion("recognise_coin >=", value, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinLessThan(Integer value) {
            addCriterion("recognise_coin <", value, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinLessThanOrEqualTo(Integer value) {
            addCriterion("recognise_coin <=", value, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinIn(List<Integer> values) {
            addCriterion("recognise_coin in", values, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinNotIn(List<Integer> values) {
            addCriterion("recognise_coin not in", values, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinBetween(Integer value1, Integer value2) {
            addCriterion("recognise_coin between", value1, value2, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andRecogniseCoinNotBetween(Integer value1, Integer value2) {
            addCriterion("recognise_coin not between", value1, value2, "recogniseCoin");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recognisesecure
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table recognisesecure
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}