package mybatis.generate.model;

import java.util.Date;

public class Recognisesecure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recognisesecure.recognise_id
     *
     * @mbg.generated
     */
    private String recogniseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recognisesecure.sender_user_id
     *
     * @mbg.generated
     */
    private Long senderUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recognisesecure.recipient_user_id
     *
     * @mbg.generated
     */
    private Long recipientUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recognisesecure.behavior_id
     *
     * @mbg.generated
     */
    private Long behaviorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recognisesecure.recognise_coin
     *
     * @mbg.generated
     */
    private Integer recogniseCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recognisesecure.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recognisesecure.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recognisesecure.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recognisesecure.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recognisesecure.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recognisesecure.recognise_id
     *
     * @return the value of recognisesecure.recognise_id
     *
     * @mbg.generated
     */
    public String getRecogniseId() {
        return recogniseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recognisesecure.recognise_id
     *
     * @param recogniseId the value for recognisesecure.recognise_id
     *
     * @mbg.generated
     */
    public void setRecogniseId(String recogniseId) {
        this.recogniseId = recogniseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recognisesecure.sender_user_id
     *
     * @return the value of recognisesecure.sender_user_id
     *
     * @mbg.generated
     */
    public Long getSenderUserId() {
        return senderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recognisesecure.sender_user_id
     *
     * @param senderUserId the value for recognisesecure.sender_user_id
     *
     * @mbg.generated
     */
    public void setSenderUserId(Long senderUserId) {
        this.senderUserId = senderUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recognisesecure.recipient_user_id
     *
     * @return the value of recognisesecure.recipient_user_id
     *
     * @mbg.generated
     */
    public Long getRecipientUserId() {
        return recipientUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recognisesecure.recipient_user_id
     *
     * @param recipientUserId the value for recognisesecure.recipient_user_id
     *
     * @mbg.generated
     */
    public void setRecipientUserId(Long recipientUserId) {
        this.recipientUserId = recipientUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recognisesecure.behavior_id
     *
     * @return the value of recognisesecure.behavior_id
     *
     * @mbg.generated
     */
    public Long getBehaviorId() {
        return behaviorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recognisesecure.behavior_id
     *
     * @param behaviorId the value for recognisesecure.behavior_id
     *
     * @mbg.generated
     */
    public void setBehaviorId(Long behaviorId) {
        this.behaviorId = behaviorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recognisesecure.recognise_coin
     *
     * @return the value of recognisesecure.recognise_coin
     *
     * @mbg.generated
     */
    public Integer getRecogniseCoin() {
        return recogniseCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recognisesecure.recognise_coin
     *
     * @param recogniseCoin the value for recognisesecure.recognise_coin
     *
     * @mbg.generated
     */
    public void setRecogniseCoin(Integer recogniseCoin) {
        this.recogniseCoin = recogniseCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recognisesecure.create_user
     *
     * @return the value of recognisesecure.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recognisesecure.create_user
     *
     * @param createUser the value for recognisesecure.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recognisesecure.create_time
     *
     * @return the value of recognisesecure.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recognisesecure.create_time
     *
     * @param createTime the value for recognisesecure.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recognisesecure.update_user
     *
     * @return the value of recognisesecure.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recognisesecure.update_user
     *
     * @param updateUser the value for recognisesecure.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recognisesecure.update_time
     *
     * @return the value of recognisesecure.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recognisesecure.update_time
     *
     * @param updateTime the value for recognisesecure.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recognisesecure.message
     *
     * @return the value of recognisesecure.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recognisesecure.message
     *
     * @param message the value for recognisesecure.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message;
    }
}