package mybatis.generate.model;

import java.util.Date;

public class Redeemsecure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redeemsecure.redeem_id
     *
     * @mbg.generated
     */
    private String redeemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redeemsecure.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redeemsecure.product_id
     *
     * @mbg.generated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redeemsecure.redeem_coin
     *
     * @mbg.generated
     */
    private Integer redeemCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redeemsecure.status_type
     *
     * @mbg.generated
     */
    private String statusType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redeemsecure.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redeemsecure.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redeemsecure.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column redeemsecure.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redeemsecure.redeem_id
     *
     * @return the value of redeemsecure.redeem_id
     *
     * @mbg.generated
     */
    public String getRedeemId() {
        return redeemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redeemsecure.redeem_id
     *
     * @param redeemId the value for redeemsecure.redeem_id
     *
     * @mbg.generated
     */
    public void setRedeemId(String redeemId) {
        this.redeemId = redeemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redeemsecure.user_id
     *
     * @return the value of redeemsecure.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redeemsecure.user_id
     *
     * @param userId the value for redeemsecure.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redeemsecure.product_id
     *
     * @return the value of redeemsecure.product_id
     *
     * @mbg.generated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redeemsecure.product_id
     *
     * @param productId the value for redeemsecure.product_id
     *
     * @mbg.generated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redeemsecure.redeem_coin
     *
     * @return the value of redeemsecure.redeem_coin
     *
     * @mbg.generated
     */
    public Integer getRedeemCoin() {
        return redeemCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redeemsecure.redeem_coin
     *
     * @param redeemCoin the value for redeemsecure.redeem_coin
     *
     * @mbg.generated
     */
    public void setRedeemCoin(Integer redeemCoin) {
        this.redeemCoin = redeemCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redeemsecure.status_type
     *
     * @return the value of redeemsecure.status_type
     *
     * @mbg.generated
     */
    public String getStatusType() {
        return statusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redeemsecure.status_type
     *
     * @param statusType the value for redeemsecure.status_type
     *
     * @mbg.generated
     */
    public void setStatusType(String statusType) {
        this.statusType = statusType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redeemsecure.create_user
     *
     * @return the value of redeemsecure.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redeemsecure.create_user
     *
     * @param createUser the value for redeemsecure.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redeemsecure.create_time
     *
     * @return the value of redeemsecure.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redeemsecure.create_time
     *
     * @param createTime the value for redeemsecure.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redeemsecure.update_user
     *
     * @return the value of redeemsecure.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redeemsecure.update_user
     *
     * @param updateUser the value for redeemsecure.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column redeemsecure.update_time
     *
     * @return the value of redeemsecure.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column redeemsecure.update_time
     *
     * @param updateTime the value for redeemsecure.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}