package mybatis.generate.model;

import java.util.Date;

public class TransactionLogsecure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_logsecure.transaction_id
     *
     * @mbg.generated
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_logsecure.from_wallet_id
     *
     * @mbg.generated
     */
    private Long fromWalletId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_logsecure.to_wallet_id
     *
     * @mbg.generated
     */
    private Long toWalletId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_logsecure.asset_name
     *
     * @mbg.generated
     */
    private String assetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_logsecure.asset_qty
     *
     * @mbg.generated
     */
    private Integer assetQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_logsecure.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transaction_logsecure.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_logsecure.transaction_id
     *
     * @return the value of transaction_logsecure.transaction_id
     *
     * @mbg.generated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_logsecure.transaction_id
     *
     * @param transactionId the value for transaction_logsecure.transaction_id
     *
     * @mbg.generated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_logsecure.from_wallet_id
     *
     * @return the value of transaction_logsecure.from_wallet_id
     *
     * @mbg.generated
     */
    public Long getFromWalletId() {
        return fromWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_logsecure.from_wallet_id
     *
     * @param fromWalletId the value for transaction_logsecure.from_wallet_id
     *
     * @mbg.generated
     */
    public void setFromWalletId(Long fromWalletId) {
        this.fromWalletId = fromWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_logsecure.to_wallet_id
     *
     * @return the value of transaction_logsecure.to_wallet_id
     *
     * @mbg.generated
     */
    public Long getToWalletId() {
        return toWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_logsecure.to_wallet_id
     *
     * @param toWalletId the value for transaction_logsecure.to_wallet_id
     *
     * @mbg.generated
     */
    public void setToWalletId(Long toWalletId) {
        this.toWalletId = toWalletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_logsecure.asset_name
     *
     * @return the value of transaction_logsecure.asset_name
     *
     * @mbg.generated
     */
    public String getAssetName() {
        return assetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_logsecure.asset_name
     *
     * @param assetName the value for transaction_logsecure.asset_name
     *
     * @mbg.generated
     */
    public void setAssetName(String assetName) {
        this.assetName = assetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_logsecure.asset_qty
     *
     * @return the value of transaction_logsecure.asset_qty
     *
     * @mbg.generated
     */
    public Integer getAssetQty() {
        return assetQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_logsecure.asset_qty
     *
     * @param assetQty the value for transaction_logsecure.asset_qty
     *
     * @mbg.generated
     */
    public void setAssetQty(Integer assetQty) {
        this.assetQty = assetQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_logsecure.create_time
     *
     * @return the value of transaction_logsecure.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_logsecure.create_time
     *
     * @param createTime the value for transaction_logsecure.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transaction_logsecure.create_user
     *
     * @return the value of transaction_logsecure.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transaction_logsecure.create_user
     *
     * @param createUser the value for transaction_logsecure.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }
}