package mybatis.generate.model;

import java.util.Date;

public class Usersecure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersecure.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersecure.client_id
     *
     * @mbg.generated
     */
    private Integer clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersecure.wallet_id
     *
     * @mbg.generated
     */
    private Long walletId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersecure.role_type
     *
     * @mbg.generated
     */
    private String roleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersecure.delete_type
     *
     * @mbg.generated
     */
    private String deleteType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersecure.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersecure.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersecure.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersecure.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersecure.user_id
     *
     * @return the value of usersecure.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersecure.user_id
     *
     * @param userId the value for usersecure.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersecure.client_id
     *
     * @return the value of usersecure.client_id
     *
     * @mbg.generated
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersecure.client_id
     *
     * @param clientId the value for usersecure.client_id
     *
     * @mbg.generated
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersecure.wallet_id
     *
     * @return the value of usersecure.wallet_id
     *
     * @mbg.generated
     */
    public Long getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersecure.wallet_id
     *
     * @param walletId the value for usersecure.wallet_id
     *
     * @mbg.generated
     */
    public void setWalletId(Long walletId) {
        this.walletId = walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersecure.role_type
     *
     * @return the value of usersecure.role_type
     *
     * @mbg.generated
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersecure.role_type
     *
     * @param roleType the value for usersecure.role_type
     *
     * @mbg.generated
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersecure.delete_type
     *
     * @return the value of usersecure.delete_type
     *
     * @mbg.generated
     */
    public String getDeleteType() {
        return deleteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersecure.delete_type
     *
     * @param deleteType the value for usersecure.delete_type
     *
     * @mbg.generated
     */
    public void setDeleteType(String deleteType) {
        this.deleteType = deleteType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersecure.create_user
     *
     * @return the value of usersecure.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersecure.create_user
     *
     * @param createUser the value for usersecure.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersecure.create_time
     *
     * @return the value of usersecure.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersecure.create_time
     *
     * @param createTime the value for usersecure.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersecure.update_user
     *
     * @return the value of usersecure.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersecure.update_user
     *
     * @param updateUser the value for usersecure.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersecure.update_time
     *
     * @return the value of usersecure.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersecure.update_time
     *
     * @param updateTime the value for usersecure.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}