package mybatis.generate.model;

import java.util.Date;

public class Walletsecure {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walletsecure.wallet_id
     *
     * @mbg.generated
     */
    private Long walletId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walletsecure.wallet_address
     *
     * @mbg.generated
     */
    private String walletAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walletsecure.private_key
     *
     * @mbg.generated
     */
    private String privateKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walletsecure.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walletsecure.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walletsecure.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column walletsecure.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walletsecure.wallet_id
     *
     * @return the value of walletsecure.wallet_id
     *
     * @mbg.generated
     */
    public Long getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walletsecure.wallet_id
     *
     * @param walletId the value for walletsecure.wallet_id
     *
     * @mbg.generated
     */
    public void setWalletId(Long walletId) {
        this.walletId = walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walletsecure.wallet_address
     *
     * @return the value of walletsecure.wallet_address
     *
     * @mbg.generated
     */
    public String getWalletAddress() {
        return walletAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walletsecure.wallet_address
     *
     * @param walletAddress the value for walletsecure.wallet_address
     *
     * @mbg.generated
     */
    public void setWalletAddress(String walletAddress) {
        this.walletAddress = walletAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walletsecure.private_key
     *
     * @return the value of walletsecure.private_key
     *
     * @mbg.generated
     */
    public String getPrivateKey() {
        return privateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walletsecure.private_key
     *
     * @param privateKey the value for walletsecure.private_key
     *
     * @mbg.generated
     */
    public void setPrivateKey(String privateKey) {
        this.privateKey = privateKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walletsecure.create_time
     *
     * @return the value of walletsecure.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walletsecure.create_time
     *
     * @param createTime the value for walletsecure.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walletsecure.create_user
     *
     * @return the value of walletsecure.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walletsecure.create_user
     *
     * @param createUser the value for walletsecure.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walletsecure.update_time
     *
     * @return the value of walletsecure.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walletsecure.update_time
     *
     * @param updateTime the value for walletsecure.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column walletsecure.update_user
     *
     * @return the value of walletsecure.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column walletsecure.update_user
     *
     * @param updateUser the value for walletsecure.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }
}